services:
  # Backend API service
  - type: web
    name: designerchat-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://designerofcontent.com
